### ISSUE TITLE
How to place a limit sell order?

### ISSUE THREAD

**Issue by ParitoshBh** [dhiaayachi/go-newton-co#1]
Hey!

This is more of a question for Newton devs but seeing that this library has a way of creating order, I thought you may have created one successfully. So in trying this library I am trying to create a limit sell order and keep getting `Problem creating order`.

An example of successful call or any pointer will be highly appreciated!

Thanks!

**Comment by dhiaayachi** [comment]
Hey!!
Sorry for the late response. Busy week ☺️

The limit order is not fully working, this is a limitation from newton.co. I opened a support.ticket with them and waiting for its resolution.
They are actively working on it. Here is a Reddit post sharing some progress.

https://www.reddit.com/r/newtonco/comments/m8pevl/state_of_the_newtonverse_friday_march_19

**Comment by swapau** [comment]
Does the orders/new endpoint work at all?

**Comment by swapau** [comment]
After checking out your code, I was able to see what I was doing wrong with authentication. I was not including the v1/.... path in the encoded signature. Thanks!

Now that I'm playing with it, I wonder if there are any options beyond LIMIT? Is there a STOP order type?

**Comment by dhiaayachi** [comment]
Here is the link to the swagger they provided me with. It has few other options.
https://github.com/docs-newton/newton-api-docs/blob/157680fd686aed5009f2ec7bd1c062bef5621c70/reference/Newton-API.v1.yaml#L213

I hope this helps 🙂

**Comment by swapau** [comment]
Thank you!
